<?php

namespace Shekel\ShekelLib\Traits;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Throwable;

trait NotFoundHandler {
    public function render($request, Throwable $e)
    {
        if ($e instanceof ModelNotFoundException) {
            return response()->json(['message' => 'Data not found'])->status(404);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
