<?php

namespace Shekel\ShekelLib\Traits;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Shekel\ShekelLib\Exceptions\ShekelInvalidArgumentException;
use Throwable;

trait NotFoundHandler {
    public function render($request, Throwable $e)
    {
        if ($e instanceof ModelNotFoundException) {
            return response()->json(['message' => 'Data not found'], 404);
        }
        if ($e instanceof ShekelInvalidArgumentException && $request->wantsJson()) {
            return response()->json(['message' => $e->getMessage()], $e->getCode() != 0 ? $e->getCode() : 400);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
